#!/usr/bin/env python3
"""Regenerate frontend/search-crawlers.conf from the engines' published ranges.

The nginx rate-limit exemption for indexing crawlers needs the network, not the
User-Agent, as proof of identity. Google and Bing publish machine-readable
lists; Yandex publishes none and asks sites to verify by reverse DNS, so its
networks are the /24s whose PTR names resolved to *.yandex.(ru|net|com) and
forward-confirmed (see YANDEX_VERIFIED_24S for the date and method).

    python3 scripts/refresh-search-crawler-ranges.py            # fetch + write
    python3 scripts/refresh-search-crawler-ranges.py --check    # fetch + diff only

A stale list is safe: an unlisted crawler IP is rate-limited like any client.
The script refuses to write if a source returns too few valid prefixes, so a
broken download cannot empty the exemption silently.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend" / "search-crawlers.conf"

GOOGLE_URL = "https://developers.google.com/static/crawling/ipranges/common-crawlers.json"
BING_URL = "https://www.bing.com/toolbox/bingbot.json"

# Observed on forecasteconomy.com 2026-10-03 (nginx security.log, ~19.7k requests,
# 504 distinct IPs): every IP with a Yandex-bot UA reverse-resolved to
# *.yandex.(ru|net|com) and the name resolved back to the same IP. These are the
# /24s those IPs belong to. Re-run the reverse+forward check before extending.
YANDEX_VERIFIED_24S = (
    "5.45.207.0/24",
    "5.255.231.0/24",
    "5.255.253.0/24",
    "45.138.0.0/24",
    "45.148.65.0/24",
    "87.250.224.0/24",
    "95.108.213.0/24",
    "213.180.203.0/24",
)

MIN_PREFIXES = {"google": 50, "bing": 10}


def fetch_prefixes(url: str) -> list[str]:
    request = urllib.request.Request(url, headers={"User-Agent": "forecasteconomy-range-refresh/1"})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = json.load(response)
    found = []
    for item in data["prefixes"]:
        value = item.get("ipv4Prefix") or item.get("ipv6Prefix")
        if value:
            found.append(str(ipaddress.ip_network(value, strict=True)))
    return found


def sort_key(prefix: str) -> tuple[int, int, int]:
    network = ipaddress.ip_network(prefix)
    return (network.version, int(network.network_address), network.prefixlen)


def geo_block(variable: str, prefixes: list[str]) -> str:
    unique = sorted(set(prefixes), key=sort_key)
    lines = [f"geo {variable} {{", "    default 0;"]
    lines += [f"    {prefix} 1;" for prefix in unique]
    lines.append("}")
    return "\n".join(lines)


def render(google: list[str], bing: list[str], today: str) -> str:
    return f"""# Verified search-crawler networks (http context). GENERATED by
# scripts/refresh-search-crawler-ranges.py on {today}; do not edit by hand.
#
# Identity is the network, never the User-Agent: a request is exempt from the
# per-IP SSR/connection limits only when BOTH its real client IP is inside the
# engine's published range AND its UA names an indexing crawler of that engine.
# A spoofed "Googlebot" from any other IP, and a browser UA from a Google IP,
# are limited like everyone else. Not exempt: GoogleOther (R&D crawler, same IP
# space as Googlebot), BingPreview, Yandex metrics/ads fetchers, AI/training
# bots. The server-wide OG-image caps (ogall/ogconn) are not per-IP and stay.
#
# Sources: Google {GOOGLE_URL}
#          Bing   {BING_URL}
#          Yandex reverse-DNS-verified /24s (see the script), no official list.
# Refresh monthly: an unlisted new crawler IP is merely limited as before.

{geo_block("$google_crawler_net", google)}

{geo_block("$bing_crawler_net", bing)}

{geo_block("$yandex_crawler_net", list(YANDEX_VERIFIED_24S))}

# $crawler_limit_key is the limit_req/limit_conn key: empty for a verified
# indexing crawler (nginx does not account an empty key), the client IP for all.
map "$google_crawler_net:$http_user_agent" $google_crawler {{
    default 0;
    "~^1:.*(?:Googlebot|Google-InspectionTool)" 1;
}}
map "$bing_crawler_net:$http_user_agent" $bing_crawler {{
    default 0;
    "~*^1:.*bingbot" 1;
}}
map "$yandex_crawler_net:$http_user_agent" $yandex_crawler {{
    default 0;
    "~*^1:.*(?:YandexBot|YandexMobileBot|YandexImages|YandexRenderResourcesBot|YandexWebmaster)" 1;
}}
map "$google_crawler$bing_crawler$yandex_crawler" $verified_search_crawler {{
    default 1;
    "000" 0;
}}
map $verified_search_crawler $crawler_limit_key {{
    1 "";
    default $binary_remote_addr;
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="print whether the file is current; do not write")
    args = parser.parse_args()

    google = fetch_prefixes(GOOGLE_URL)
    bing = fetch_prefixes(BING_URL)
    for name, found in (("google", google), ("bing", bing)):
        if len(found) < MIN_PREFIXES[name]:
            print(f"refusing to continue: {name} returned {len(found)} prefixes", file=sys.stderr)
            return 2

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    text = render(google, bing, today)
    current = OUTPUT.read_text() if OUTPUT.exists() else ""
    strip_date = lambda s: "\n".join(line for line in s.splitlines() if "GENERATED by" not in line)
    same = strip_date(current) == strip_date(text)
    print(f"google={len(set(google))} bing={len(set(bing))} yandex={len(YANDEX_VERIFIED_24S)} "
          f"{'unchanged' if same else 'CHANGED'}")
    if args.check:
        return 0 if same else 1
    if not same:
        OUTPUT.write_text(text)
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
